"""empty message

Revision ID: 4c4b7107dfd3
Revises: b2bfb4a1da83
Create Date: 2022-01-30 19:59:52.941446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c4b7107dfd3'
down_revision = 'b2bfb4a1da83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('Artist', 'looking_for_venue')
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('Shows', 'date')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Shows', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Shows', 'start_time')
    op.add_column('Artist', sa.Column('looking_for_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
