"""empty message

Revision ID: e7f860624524
Revises: 4c4b7107dfd3
Create Date: 2022-02-03 16:08:13.190274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f860624524'
down_revision = '4c4b7107dfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('Shows_venue_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_artist_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Shows', 'artist')
    op.drop_column('Shows', 'venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_artist_fkey', 'Shows', 'Artist', ['artist'], ['id'])
    op.create_foreign_key('Shows_venue_fkey', 'Shows', 'Venue', ['venue'], ['id'])
    op.drop_column('Shows', 'artist_id')
    op.drop_column('Shows', 'venue_id')
    # ### end Alembic commands ###
